### Reads three csv files in the format generated by frequency analyser.py
### Plots the 3d graph representation of the associated recorded signal

import numpy as np
import matplotlib.pyplot as plt


time = np.genfromtxt('X.csv', delimiter=',')
frequency = np.genfromtxt('Y.csv', delimiter=',')
Z = np.genfromtxt('Z.csv', delimiter=',')
peaks = np.genfromtxt('fres_analysis.csv', delimiter = ',')

X=np.zeros((1,len(time)),float)
Y=np.zeros((len(frequency),1),float)


for i in range(len (time)):
    X[0][i]=time[i]
    
for i in range(len(frequency)):
    Y[i][0]=frequency[i]
    


    
fig = plt.figure(figsize =(14, 9))
ax = plt.axes()

for i in range(peaks.shape[0]):
    ax.plot(peaks[i], time, ',', color='black')

ax.set_title('plot of local peaks')

ax.set_xlabel('frequencies (Hz)')
ax.set_ylabel('time (s)')

plt.show()
